language: php

php:
  - 5.4
  - 5.3
  - 5.5

before_script:
 - composer self-update
 - composer install --prefer-source --dev
 
script:
  - mkdir -p build/logs
  - phpunit --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
